# This workflow will install Python dependencies, and then run the main.py script
# BBT

name: sleepIRv2

on:
  schedule:
    - cron: '0 22 * * 4'
    - cron: '0 15 * * 0,6'
  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    environment: sleeper

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: execute py script
      env: 
        LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        PHONE_FROM: ${{ secrets.PHONE_FROM }}
        PHONE_TO: ${{ secrets.PHONE_TO }}
        TWILIO_ACCOUNT_SID: ${{ secrets.LEAGUE_ID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.LEAGUE_ID }}
      run: python main.py
      
